In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv(r"/content/phishing_site_urls.csv")

In [3]:
data.head()

URL Label
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...   bad
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...   bad
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....   bad
3  mail.printakid.com/www.online.americanexpress....   bad
4  thewhiskeydregs.com/wp-content/themes/widescre...   bad

In [4]:
data.tail()

URL Label
498629  multipler04622.top/   bad
498630   bestdeal34771.win/   bad
498631   obbilistation.com/   bad
498632   multipler0927.win/   bad
498633     west-side74.win/   NaN

In [5]:
data.sample(10)

URL Label
206671  laurindo-almeida.blogspot.com/2006/12/spanish-...  good
78295                    www.robvanderwoude.com/rexx.html  good
450448  transitmiami.com/fdot/a-macarthur-causeway-pro...  good
203797                         jptscareband.blogspot.com/  good
402868      neilbrown.newcastlefans.com/albion/albion.htm  good
249523  travel.yahoo.com/p-travelguide-2775510-golf_d_...  good
55576   www.sba.gov/category/navigation-structure/coun...  good
388408  metrolyrics.com/imparfait-lyrics-belanger-dani...  good
144505                      arkansas.jobs.topusajobs.com/  good
132030                           webtv.by/logs/Paypal.htm   bad

In [6]:
data.shape

(498634, 2)

In [7]:
data.size

997268

In [8]:
data.describe()

URL   Label
count                    498634  498633
unique                   491432       2
top     103.234.36.75/rd927.exe    good
freq                         27  392924

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 498634 entries, 0 to 498633
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype 
---  ------  --------------   ----- 
 0   URL     498634 non-null  object
 1   Label   498633 non-null  object
dtypes: object(2)
memory usage: 7.6+ MB


In [10]:
data.URL

0         nobell.it/70ffb52d079109dca5664cce6f317373782/...
1         www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...
2         serviciosbys.com/paypal.cgi.bin.get-into.herf....
3         mail.printakid.com/www.online.americanexpress....
4         thewhiskeydregs.com/wp-content/themes/widescre...
                                ...                        
498629                                  multipler04622.top/
498630                                   bestdeal34771.win/
498631                                   obbilistation.com/
498632                                   multipler0927.win/
498633                                     west-side74.win/
Name: URL, Length: 498634, dtype: object

In [11]:
data.Label

0         bad
1         bad
2         bad
3         bad
4         bad
         ... 
498629    bad
498630    bad
498631    bad
498632    bad
498633    NaN
Name: Label, Length: 498634, dtype: object

In [12]:
data.isnull().sum()

URL      0
Label    1
dtype: int64

In [13]:
data.Label.value_counts()

Label
good    392924
bad     105709
Name: count, dtype: int64

In [14]:
good = data[data.Label == "good"]
bad = data[data.Label == "bad"]

In [15]:
good.shape

(392924, 2)

In [16]:
good.head()

URL Label
18231  esxcc.com/js/index.htm?us.battle.net/noghn/en/...  good
18232  wwweira¯&nvinip¿ncH¯wVö%ÆåyDaHðû/ÏyEùuË\nÓ6...  good
18233  'www.institutocgr.coo/web/media/syqvem/dk-óij...  good
18234                  Yìê‡
koãջΧDéÎl½ñ¡ââqtò¸/à; Í  good
18236  ruta89fm.com/images/AS@Vies/1i75cf7b16vc<Fd16...  good

In [17]:
good.sample(10)

URL Label
392262   motortrend.com/used_cars/11/chevrolet/el_camino/  good
467642            xtralyrics.com/lyrics/hatenai_sora.aspx  good
432198  slideshare.net/garr/quotes-lessons-from-comedi...  good
208639  local.yahoo.com/WI/Argonne/Travel+Lodging/Hote...  good
334400    fanbase.com/Iowa-State-Cyclones-Mens-Basketball  good
426031      rozanehmagazine.com/NoveDec05/PARTIIAzar.html  good
67654                         tools.ietf.org/html/rfc1757  good
303128                                charlesrknight.com/  good
308191     comfortsuites.com/hotel-monroe-louisiana-LA001  good
334771  fandango.com/burnafterreading_112278/movieover...  good

In [18]:
bad.shape

(105709, 2)

In [19]:
bad.head()

URL Label
0  nobell.it/70ffb52d079109dca5664cce6f317373782/...   bad
1  www.dghjdgf.com/paypal.co.uk/cycgi-bin/webscrc...   bad
2  serviciosbys.com/paypal.cgi.bin.get-into.herf....   bad
3  mail.printakid.com/www.online.americanexpress....   bad
4  thewhiskeydregs.com/wp-content/themes/widescre...   bad

In [20]:
bad.sample(10)

URL Label
111133  stylefurniture.com.pk/wp-admin/dropbox2016/Hom...   bad
99134   sign-in.paypal-update-security.webapps.ejjje8x...   bad
21584   'update-information002.mpd.ly/?/cgi- bin/websc...   bad
495500                        uwdbplf.chromeupdater.site/   bad
39686                 www.mcamq.info/page/vote.php?pid=77   bad
42941   793701101.dt532l523se41r4.793701101.13ve123r.s...   bad
490735                  seminee.aega.ro/e7/cp.php?m=login   bad
101407                        krymtur.com/web/webscr9182/   bad
112688  boomsavings.com/watch/Proizvod/LoginVerificati...   bad
6933    www.ginkel.nl/modules/mod_index_cadastrar_clie...   bad

In [21]:
good = good.sample(n=156422)
good.shape

(156422, 2)

In [22]:
bad.shape

(105709, 2)

In [23]:
data = pd.concat([good, bad], axis=0)

In [24]:
data.head()

URL Label
296461          buddytv.com/jack-davenport.aspx  good
174888              en.wikipedia.org/wiki/Fuchs  good
398333                    myspace.com/495877919  good
357521              imdb.com/company/co0064070/  good
207638  library.sc.edu/music/south_america.html  good

In [25]:
data.shape

(262131, 2)

In [26]:
data.Label.value_counts()

Label
good    156422
bad     105709
Name: count, dtype: int64

In [27]:
import time
import nltk
from nltk.corpus import stopwords
import re
from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer
from nltk.stem.snowball import SnowballStemmer
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [28]:
tokenizer = RegexpTokenizer(r'[A-Za-z]+')

In [29]:
data.URL[0]

'nobell.it/70ffb52d079109dca5664cce6f317373782/login.SkyPe.com/en/cgi-bin/verification/login/70ffb52d079109dca5664cce6f317373/index.php?cmd=_profile-ach&outdated_page_tmpl=p/gen/failed-to-load&nav=0.5.1&login_access=1322408526'

In [30]:
tokenizer.tokenize(data.URL[0])

['nobell',
 'it',
 'ffb',
 'd',
 'dca',
 'cce',
 'f',
 'login',
 'SkyPe',
 'com',
 'en',
 'cgi',
 'bin',
 'verification',
 'login',
 'ffb',
 'd',
 'dca',
 'cce',
 'f',
 'index',
 'php',
 'cmd',
 'profile',
 'ach',
 'outdated',
 'page',
 'tmpl',
 'p',
 'gen',
 'failed',
 'to',
 'load',
 'nav',
 'login',
 'access']

In [31]:
print('Getting words tokenized ...')
t0= time.perf_counter()
data['text_tokenized'] = data.URL.map(lambda t: tokenizer.tokenize(t)) # doing with all rows
t1 = time.perf_counter() - t0
print('Time taken',t1 ,'sec')

Getting words tokenized ...
Time taken 2.1103729069999986 sec


In [32]:
data.sample(5)

URL Label  \
87090                            www.osnews.com/story/93/  good   
205235                                kevinhermening.com/  good   
403421  netprospex.com/company/executives/Matson-Navig...  good   
265302                                 1stopmattress.com/  good   
121842          storybookalpacas.com/account4/index2.html   bad   

                                           text_tokenized  
87090                           [www, osnews, com, story]  
205235                              [kevinhermening, com]  
403421  [netprospex, com, company, executives, Matson,...  
265302                                [stopmattress, com]  
121842      [storybookalpacas, com, account, index, html]

In [33]:
stemmer = SnowballStemmer("english")

In [34]:
print('Getting words stemmed ...')
t0= time.perf_counter()
data['text_stemmed'] = data['text_tokenized'].map(lambda l: [stemmer.stem(word) for word in l])
t1= time.perf_counter() - t0
print('Time taken',t1 ,'sec')

Getting words stemmed ...
Time taken 23.628793900999995 sec


In [35]:
data.sample(5)

URL Label  \
78430                listserv.uga.edu/archives/sas-l.html  good   
491888                             37.57.144.177/se77.avi   bad   
129676  burinvest.co.mz/components/com_content/secured...   bad   
10564   px-coding.org/mobile/bin/_id/www.paypal.com/fr...   bad   
101954                        popin-stoffwindeln.de/docs/   bad   

                                           text_tokenized  \
78430        [listserv, uga, edu, archives, sas, l, html]   
491888                                          [se, avi]   
129676  [burinvest, co, mz, components, com, content, ...   
10564   [px, coding, org, mobile, bin, id, www, paypal...   
101954                    [popin, stoffwindeln, de, docs]   

                                             text_stemmed  
78430          [listserv, uga, edu, archiv, sas, l, html]  
491888                                          [se, avi]  
129676  [burinvest, co, mz, compon, com, content, secu...  
10564   [px, code, org, mobil, bin, id, www, paypal, c...  
101954                     [popin, stoffwindeln, de, doc]

In [36]:
print('Getting joiningwords ...')
t0= time.perf_counter()
data['text_sent'] = data['text_stemmed'].map(lambda l: ' '.join(l))
t1= time.perf_counter() - t0
print('Time taken',t1 ,'sec')

Getting joiningwords ...
Time taken 0.1360153050000008 sec


In [37]:
data.sample(5)

URL Label  \
479549  zimbio.com/Libya/articles/Y9x8mN6WRij/Transiti...  good   
10851   www.bikerboyzsg.org/aaa/BtoChannelDriver.ssobt...   bad   
108066      bayviewbakkhali.co.in/ggdcfrolola/s/index.php   bad   
117003       naturaldesignstones.com/4l7sq/gdoc/index.php   bad   
9075                    pastehtml.com/view/becf2akad.html   bad   

                                           text_tokenized  \
479549  [zimbio, com, Libya, articles, Y, x, mN, WRij,...   
10851   [www, bikerboyzsg, org, aaa, BtoChannelDriver,...   
108066  [bayviewbakkhali, co, in, ggdcfrolola, s, inde...   
117003  [naturaldesignstones, com, l, sq, gdoc, index,...   
9075             [pastehtml, com, view, becf, akad, html]   

                                             text_stemmed  \
479549  [zimbio, com, libya, articl, y, x, mn, wrij, t...   
10851   [www, bikerboyzsg, org, aaa, btochanneldriv, s...   
108066  [bayviewbakkhali, co, in, ggdcfrolola, s, inde...   
117003  [naturaldesignston, com, l, sq, gdoc, index, php]   
9075             [pastehtml, com, view, becf, akad, html]   

                                                text_sent  
479549  zimbio com libya articl y x mn wrij transit go...  
10851   www bikerboyzsg org aaa btochanneldriv ssobto htm  
108066      bayviewbakkhali co in ggdcfrolola s index php  
117003          naturaldesignston com l sq gdoc index php  
9075                    pastehtml com view becf akad html

In [38]:
data = data.drop(['URL', 'text_tokenized', 'text_stemmed'], axis = 1)
data.head()

Label                                text_sent
296461  good          buddytv com jack davenport aspx
174888  good               en wikipedia org wiki fuch
398333  good                               myspac com
357521  good                      imdb com compani co
207638  good  librari sc edu music south america html

In [39]:
X = data.text_sent.values

In [40]:
Y = data.Label.values

In [41]:
X.shape

(262131,)

In [42]:
Y.shape

(262131,)

In [43]:
vector = TfidfVectorizer()
vector.fit(X)
X = vector.transform(X)

In [44]:
X.shape

(262131, 230379)

In [45]:
print(X)

  (0, 11995)	0.2775597887446501
  (0, 26515)	0.5745908446662452
  (0, 38618)	0.0767433600570903
  (0, 46195)	0.6116587319043673
  (0, 98636)	0.4612916401475808
  (1, 60285)	0.27852387427134045
  (1, 73357)	0.7949559771632607
  (1, 146541)	0.24708688027441453
  (1, 215724)	0.3292065972594985
  (1, 215756)	0.3479088037839333
  (2, 38618)	0.20721761279119327
  (2, 134166)	0.9782948742322629
  (3, 37649)	0.44307340435402204
  (3, 38618)	0.13446365965829607
  (3, 39012)	0.6398840492998823
  (3, 93764)	0.6133138560614957
  (4, 7364)	0.4449499813240025
  (4, 57645)	0.29046925518902744
  (4, 89941)	0.1625159285186963
  (4, 114988)	0.3651000778650278
  (4, 132885)	0.3418167924186473
  (4, 174442)	0.4579357800087935
  (4, 183380)	0.48103402565590236
  (5, 38618)	0.0874253789434664
  (5, 89941)	0.18079700773720409
  :	:
  (262123, 204384)	0.36647115761093985
  (262124, 50894)	0.28578932159640147
  (262124, 152912)	0.17499731769929006
  (262124, 163253)	0.7311277035314153
  (262124, 204384)	0.3406

In [46]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify = Y,random_state = 2)

In [47]:
print(X_train)

  (0, 10331)	0.28062996170409366
  (0, 38618)	0.1278237225221376
  (0, 89941)	0.13217069705112353
  (0, 120899)	0.3002596814624568
  (0, 131746)	0.4155882128523016
  (0, 154841)	0.5492142469783685
  (0, 223000)	0.5682720293467207
  (1, 74582)	0.4103511911262077
  (1, 75756)	0.6553583725098182
  (1, 107205)	0.475335016447028
  (1, 152912)	0.15686173122294014
  (1, 155983)	0.3547526758633369
  (1, 219288)	0.16037101330175865
  (2, 22240)	0.1483330149486356
  (2, 29089)	0.166529771268365
  (2, 34779)	0.21650676146465198
  (2, 38618)	0.03506735845810171
  (2, 69784)	0.2174862217366473
  (2, 87803)	0.18948865192728165
  (2, 112039)	0.31922039612300473
  (2, 114216)	0.27604962533458866
  (2, 118043)	0.2589925857585304
  (2, 122473)	0.531185884275494
  (2, 144840)	0.21156564519784446
  (2, 148954)	0.2834687601328329
  :	:
  (209700, 38618)	0.11469172960615792
  (209700, 59778)	0.24406777226003237
  (209700, 68652)	0.5391229351346261
  (209700, 114988)	0.26642306093163215
  (209700, 133533)	0.

In [48]:
Y_train

array(['good', 'bad', 'good', ..., 'good', 'good', 'good'], dtype=object)

In [49]:
print(Y_train)

['good' 'bad' 'good' ... 'good' 'good' 'good']


In [50]:
X_test

<52427x230379 sparse matrix of type '<class 'numpy.float64'>'
	with 392299 stored elements in Compressed Sparse Row format>

In [51]:
print(X_test)

  (0, 6262)	0.31045266139964306
  (0, 6419)	0.47468165203838236
  (0, 18218)	0.5034379621336083
  (0, 38618)	0.06316515857484391
  (0, 60285)	0.1818627404343726
  (0, 88655)	0.4248543130158781
  (0, 89935)	0.1661896034357891
  (0, 94358)	0.16537784109425374
  (0, 97395)	0.39027272132616464
  (1, 4440)	0.36306924912581096
  (1, 21291)	0.20050438363571507
  (1, 62711)	0.36306924912581096
  (1, 110177)	0.2948528178169842
  (1, 111471)	0.27002505317073433
  (1, 113320)	0.36306924912581096
  (1, 119627)	0.2880263855329229
  (1, 150727)	0.28191521130926617
  (1, 152912)	0.10180880003098684
  (1, 157213)	0.24116962126524408
  (1, 175689)	0.24455160338158338
  (1, 201512)	0.29689060941073636
  (1, 213956)	0.1599240940496061
  (2, 38618)	0.09441877178423347
  (2, 115639)	0.502339219874648
  (2, 167332)	0.8595000894185449
  :	:
  (52424, 16550)	0.35230093557058567
  (52424, 60285)	0.14126698080576963
  (52424, 61047)	0.2695548112660319
  (52424, 89941)	0.10146779858337018
  (52424, 117383)	0.261

In [52]:
Y_test

array(['good', 'bad', 'good', ..., 'bad', 'bad', 'good'], dtype=object)

In [53]:
print(Y_test)

['good' 'bad' 'good' ... 'bad' 'bad' 'good']


In [54]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [55]:
Y_train = le.fit_transform(Y_train)
Y_train

array([1, 0, 1, ..., 1, 1, 1])

In [56]:
Y_test = le.fit_transform(Y_test)
Y_test

array([1, 0, 1, ..., 0, 0, 1])

In [57]:
model = LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

In [58]:
model.predict(X_test)

array([1, 0, 1, ..., 0, 0, 1])

In [59]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [60]:
training_data_accuracy

0.9642400717201388

In [61]:
X_test_prediction = model.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [62]:
testing_data_accuracy

0.9501974173612833

In [63]:
data.text_sent[0]

'nobel it ffb d dca cce f login skype com en cgi bin verif login ffb d dca cce f index php cmd profil ach outdat page tmpl p gen fail to load nav login access'

In [64]:
testing = data.text_sent[0]
testing = [testing]
testing = vector.transform(testing)
model.predict(testing)

array([0])

In [65]:
import pickle
with open('model.pickle', 'wb') as file:
     pickle.dump(model, file)

In [66]:
with open('model.pickle', 'rb') as file:
     model = pickle.load(file)

In [67]:
testing = "www.google.com"
testing = [testing]
testing = vector.transform(testing)
prediction=model.predict(testing)
if prediction == 0:
    print("Fake Website")
else:
    print("Real Website")

Real Website


In [68]:
testing = "www.xyzxcf"
testing = [testing]
testing = vector.transform(testing)
prediction=model.predict(testing)
if prediction == 0:
    print("Fake Website")
else:
    print("Real Website")

Real Website


In [69]:
testing = "www.facebook.com"
testing = [testing]
testing = vector.transform(testing)
prediction=model.predict(testing)
if prediction == 0:
    print("Fake Website")
else:
    print("Real Website")

Real Website


In [70]:
testing = "w.xyzxcf"
testing = [testing]
testing = vector.transform(testing)
prediction=model.predict(testing)
if prediction == 0:
    print("Fake Website")
else:
    print("Real Website")

Real Website


In [71]:
testing = "w.vgffh"
testing = [testing]
testing = vector.transform(testing)
prediction=model.predict(testing)
if prediction == 0:
    print("Fake Website")
else:
    print("Real Website")

Real Website


In [72]:
testing = "www.google.com"
testing = [testing]
testing = vector.transform(testing)
prediction=model.predict(testing)
if prediction == 0:
    print("Fake Website")
else:
    print("Real Website")

Real Website
